swagger: '2.0'
info:
  version: 1.0.0
  title: 'Novacast Event Service API'
basePath: /api/v1
produces:
  - application/json
consumes:
  - application/json
securityDefinitions:
  accessKey:
    type: apiKey
    in: query
    name: access_token
  appSecret:
    type: apiKey
    in: query
    name: app_token
  previewToken:
    type: apiKey
    in: query
    name: preview_token
security:
  - accessKey: []
paths:
  $spec_ref: 'paths'
definitions:
  $spec_ref: 'models'