swagger: '2.0'
info:
  version: 1.0.0
  title: 'Novacast Identity Service API'
basePath: /api/v1
produces:
  - application/json
consumes:
  - application/json
securityDefinitions:
  accessKey:
    type: apiKey
    in: query
    name: access_token
  appSecret:
    type: apiKey
    in: query
    name: app_token
security:
  - accessKey: []
  - appSecret: []
paths:
  /accounts:
    post:
      operationId: createAccount
      description: |
        Creates a new `Account`
      parameters:
        - name: account_info
          description: Account Information
          in: body
          required: true
          schema:
            $ref: '#/definitions/AccountRequest'
      responses:
        '201':
          description: Account created
          schema:
            $ref: '#/definitions/Account'
        default:
          description: Account creation failed
          schema:
            $ref: '#/definitions/Error'
  /accounts/{account_uid}:
    get:
      operationId: getAccount
      description: |
        Gets the `User` object for the account
      parameters:
        - name: account_uid
          in: path
          required: true
          type: string
          description: Account UID
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Account'
        default:
          description: Error response
          schema:
            $ref: '#/definitions/Error'
  /access_tokens/{access_token}:
    get:
      operationId: validateToken
      description: |
        Validates an access token
      parameters:
        - name: access_token
          description: Access token
          type: string
          in: path
          required: true
      security:
        - appSecret: []
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Account'
        default:
          description: Error response
          schema:
            $ref: '#/definitions/Error'
definitions:
  AccountRequest:
    type: object
    title: Account Request Information
    properties:
      domain_name:
        description: Domain name
        type: string
      provider_name:
        description: OAuth provider name
        type: string
      identifier:
        description: Account identifier (username or email)
        type: string
      password:
        description: Account password
        type: string
      access_token:
        description: Access token provided by a third party OAuth provider
        type: string
    required: ['domain_name', 'provider_name']
  Account:
    type: object
    properties:
      uid:
        type: string
        description: Account Unique ID
      identifier:
        type: string
        description: Account identifier (username or email)
      domain_id:
        type: integer
        description: Domain Id
    required: ['uid', 'identifier', 'domain_id']
  Error:
    type: object
    properties:
      klass_name:
        description: Error class name
        type: string
      messages:
        description: An array of error messages
        type: array
        items:
          type: string
